spring:
  datasource:
    url: jdbc:postgresql://localhost/dictionary
    username: postgres
    password: password
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailtrap.io
    port: 25
    username: fefbfa42f717fe
    password: 10cdf99e31b616
